### PR TITLE
PR51 rebase

### PR DESCRIPTION
**Pull request by samuelsov**
Simple rebase of PR51 to make it work with current master.

### CODE REVIEW

**Comment by jake-mw** [comment]
Thanks @adixon and @samuelsov

**Comment by KarinG** [comment]
@samuelsov - thank you for having this live/using it on two projects. I am a big fan of evidence based merging.

**Comment by adixon** [comment]
Hey wait @KarinG , I've had this running on a few sites for almost three years! Where's my credit? 

But seriously .. thanks @samuelsov for the rebase!

**Comment by KarinG** [comment]
:-) Thank you @adixon - coffee coming your way soon.

**Comment by KarinG** [comment]
Ai -> 
https://github.com/jake-mw/CDNTaxReceipts/blob/master/CRM/Cdntaxreceipts/Form/Settings.php#L144

**Pull request merged**
